version: '3.9'

services:
  api-service:
    container_name: car-api-gateway
    build: .
    networks:
      - ntwrk
    ports:
      - "8080:8080"

networks:
  ntwrk:
    external: true

volumes:
  db-data:
